[VERSION]
VERSIONNUMBER=64

[SCENARIODATA]
TITLE = Barents Sea 1
FINISH_TIME_HOUR=9
FINISH_TIME_MINUTE=0

[SHIP0]

SIDE = ROYAL NAVY
NAME = ONSLOW
SHORTNAME = Onslow
TYPE = DD
CLASS = OP Class
STATUS = SHIP_SUNK
XPOSITION = 523.1762695
ZPOSITION = 2106.779785
SPEED = 8.000000669
HEADING = 85
CURRENTHITPOINTS = 2497
CURRENTFLOATPOINTS = 1827
CURRENTFIRECOUNT = 0

PROPULSIONSYSTEMPERCENTAGE = 100
PROPULSIONSYSTEMDAMAGE = SYSTEM_OK
MANUEVERSYSTEMDIRECTION = Center
MANUEVERSYSTEMDAMAGE = 0
RADARDAMAGE = SYSTEM_OK
ELECTRICALSYSTEMDAMAGE = 0
BRIDGEDAMAGE = 0
DAMAGECONTROLPERCENTAGE = 100
DAMAGECONTROLDAMAGE = 0
SEARCHLIGHTP1DAMAGE = SYSTEM_OK
SEARCHLIGHTS1DAMAGE = SYSTEM_OK
TERTIARYGUNSCNT = 0
CIWPERCENTAGE = 100
CIWDAMAGE = 0
DIRECTOR1DAMAGE = SYSTEM_OK
DIRECTOR2DAMAGE = SYSTEM_OK
TORPMOUNT1TORPSLEFT = 4
TORPMOUNT1DAMAGE = SYSTEM_OK
TORPMOUNT2TORPSLEFT = 4
TORPMOUNT2DAMAGE = SYSTEM_OK

SECONDARYMAGDAMAGE = SYSTEM_OK
SECONDARYMAGHE = 0
SECONDARYMAGAP = 0
SECONDARYMAGCOM = 0
MGTA = SYSTEM_OK
MGTB = SYSTEM_OK
MGTY = SYSTEM_OK
MGTZ = SYSTEM_OK
MAGADAMAGE = SYSTEM_OK
MAGAHE = 0
MAGAAP = 0
MAGACOM = 500
MAGBDAMAGE = SYSTEM_OK
MAGBHE = 0
MAGBAP = 0
MAGBCOM = 500

[SHIP1]

SIDE = ROYAL NAVY
NAME = ORWELL
SHORTNAME = Orwell
TYPE = DD
CLASS = OP Class
STATUS = SHIP_SUNK
XPOSITION = -205.5601196
ZPOSITION = 2043.02356
SPEED = 8.000000669
HEADING = 85
CURRENTHITPOINTS = 2497
CURRENTFLOATPOINTS = 1827
CURRENTFIRECOUNT = 0

PROPULSIONSYSTEMPERCENTAGE = 100
PROPULSIONSYSTEMDAMAGE = SYSTEM_OK
MANUEVERSYSTEMDIRECTION = Center
MANUEVERSYSTEMDAMAGE = 0
RADARDAMAGE = SYSTEM_OK
ELECTRICALSYSTEMDAMAGE = 0
BRIDGEDAMAGE = 0
DAMAGECONTROLPERCENTAGE = 100
DAMAGECONTROLDAMAGE = 0
SEARCHLIGHTP1DAMAGE = SYSTEM_OK
SEARCHLIGHTS1DAMAGE = SYSTEM_OK
TERTIARYGUNSCNT = 0
CIWPERCENTAGE = 100
CIWDAMAGE = 0
DIRECTOR1DAMAGE = SYSTEM_OK
DIRECTOR2DAMAGE = SYSTEM_OK
TORPMOUNT1TORPSLEFT = 4
TORPMOUNT1DAMAGE = SYSTEM_OK
TORPMOUNT2TORPSLEFT = 4
TORPMOUNT2DAMAGE = SYSTEM_OK

SECONDARYMAGDAMAGE = SYSTEM_OK
SECONDARYMAGHE = 0
SECONDARYMAGAP = 0
SECONDARYMAGCOM = 0
MGTA = SYSTEM_OK
MGTB = SYSTEM_OK
MGTY = SYSTEM_OK
MGTZ = SYSTEM_OK
MAGADAMAGE = SYSTEM_OK
MAGAHE = 0
MAGAAP = 0
MAGACOM = 500
MAGBDAMAGE = SYSTEM_OK
MAGBHE = 0
MAGBAP = 0
MAGBCOM = 500

[SHIP2]

SIDE = ROYAL NAVY
NAME = OBEDIENT
SHORTNAME = Obedient
TYPE = DD
CLASS = OP Class
STATUS = SHIP_SUNK
XPOSITION = -848.4124756
ZPOSITION = -2200.043945
SPEED = 8.000000669
HEADING = 85
CURRENTHITPOINTS = 2497
CURRENTFLOATPOINTS = 1827
CURRENTFIRECOUNT = 0

PROPULSIONSYSTEMPERCENTAGE = 100
PROPULSIONSYSTEMDAMAGE = SYSTEM_OK
MANUEVERSYSTEMDIRECTION = Center
MANUEVERSYSTEMDAMAGE = 0
RADARDAMAGE = SYSTEM_OK
ELECTRICALSYSTEMDAMAGE = 0
BRIDGEDAMAGE = 0
DAMAGECONTROLPERCENTAGE = 100
DAMAGECONTROLDAMAGE = 0
SEARCHLIGHTP1DAMAGE = SYSTEM_OK
SEARCHLIGHTS1DAMAGE = SYSTEM_OK
TERTIARYGUNSCNT = 0
CIWPERCENTAGE = 100
CIWDAMAGE = 0
DIRECTOR1DAMAGE = SYSTEM_OK
DIRECTOR2DAMAGE = SYSTEM_OK
TORPMOUNT1TORPSLEFT = 4
TORPMOUNT1DAMAGE = SYSTEM_OK
TORPMOUNT2TORPSLEFT = 4
TORPMOUNT2DAMAGE = SYSTEM_OK

SECONDARYMAGDAMAGE = SYSTEM_OK
SECONDARYMAGHE = 0
SECONDARYMAGAP = 0
SECONDARYMAGCOM = 0
MGTA = SYSTEM_OK
MGTB = SYSTEM_OK
MGTY = SYSTEM_OK
MGTZ = SYSTEM_OK
MAGADAMAGE = SYSTEM_OK
MAGAHE = 0
MAGAAP = 0
MAGACOM = 500
MAGBDAMAGE = SYSTEM_OK
MAGBHE = 0
MAGBAP = 0
MAGBCOM = 500

[SHIP3]

SIDE = ROYAL NAVY
NAME = OBDURATE
SHORTNAME = Obdurate
TYPE = DD
CLASS = OP Class
STATUS = SHIP_SUNK
XPOSITION = -1577.148804
ZPOSITION = -2263.800293
SPEED = 8.000000669
HEADING = 85
CURRENTHITPOINTS = 2497
CURRENTFLOATPOINTS = 1827
CURRENTFIRECOUNT = 0

PROPULSIONSYSTEMPERCENTAGE = 100
PROPULSIONSYSTEMDAMAGE = SYSTEM_OK
MANUEVERSYSTEMDIRECTION = Center
MANUEVERSYSTEMDAMAGE = 0
RADARDAMAGE = SYSTEM_OK
ELECTRICALSYSTEMDAMAGE = 0
BRIDGEDAMAGE = 0
DAMAGECONTROLPERCENTAGE = 100
DAMAGECONTROLDAMAGE = 0
SEARCHLIGHTP1DAMAGE = SYSTEM_OK
SEARCHLIGHTS1DAMAGE = SYSTEM_OK
TERTIARYGUNSCNT = 0
CIWPERCENTAGE = 100
CIWDAMAGE = 0
DIRECTOR1DAMAGE = SYSTEM_OK
DIRECTOR2DAMAGE = SYSTEM_OK
TORPMOUNT1TORPSLEFT = 4
TORPMOUNT1DAMAGE = SYSTEM_OK
TORPMOUNT2TORPSLEFT = 4
TORPMOUNT2DAMAGE = SYSTEM_OK

SECONDARYMAGDAMAGE = SYSTEM_OK
SECONDARYMAGHE = 0
SECONDARYMAGAP = 0
SECONDARYMAGCOM = 0
MGTA = SYSTEM_OK
MGTB = SYSTEM_OK
MGTY = SYSTEM_OK
MGTZ = SYSTEM_OK
MAGADAMAGE = SYSTEM_OK
MAGAHE = 0
MAGAAP = 0
MAGACOM = 500
MAGBDAMAGE = SYSTEM_OK
MAGBHE = 0
MAGBAP = 0
MAGBCOM = 500

[SHIP4]

SIDE = ROYAL NAVY
NAME = ACHATES
SHORTNAME = Achates
TYPE = DD
CLASS = AB Class
STATUS = SHIP_SUNK
XPOSITION = -1226.496582
ZPOSITION = -9.93829155
SPEED = 8.000000669
HEADING = 85
CURRENTHITPOINTS = 1815
CURRENTFLOATPOINTS = 1389
CURRENTFIRECOUNT = 0

PROPULSIONSYSTEMPERCENTAGE = 100
PROPULSIONSYSTEMDAMAGE = SYSTEM_OK
MANUEVERSYSTEMDIRECTION = Center
MANUEVERSYSTEMDAMAGE = 0
RADARDAMAGE = SYSTEM_OK
ELECTRICALSYSTEMDAMAGE = 0
BRIDGEDAMAGE = 0
DAMAGECONTROLPERCENTAGE = 100
DAMAGECONTROLDAMAGE = 0
SEARCHLIGHTP1DAMAGE = SYSTEM_OK
SEARCHLIGHTS1DAMAGE = SYSTEM_OK
TERTIARYGUNSCNT = 0
CIWPERCENTAGE = 100
CIWDAMAGE = 0
DIRECTOR1DAMAGE = SYSTEM_OK
DIRECTOR2DAMAGE = SYSTEM_OK
TORPMOUNT1TORPSLEFT = 4
TORPMOUNT1DAMAGE = SYSTEM_OK
TORPMOUNT2TORPSLEFT = 0
TORPMOUNT2DAMAGE = SYSTEM_OK

SECONDARYMAGDAMAGE = SYSTEM_OK
SECONDARYMAGHE = 0
SECONDARYMAGAP = 0
SECONDARYMAGCOM = 0
MGTA = SYSTEM_OK
MGTB = SYSTEM_OK
MGTY = SYSTEM_OK
MGTZ = SYSTEM_OK
MAGADAMAGE = SYSTEM_OK
MAGAHE = 0
MAGAAP = 0
MAGACOM = 380
MAGBDAMAGE = SYSTEM_OK
MAGBHE = 0
MAGBAP = 0
MAGBCOM = 380

[SHIP5]

SIDE = ROYAL NAVY
NAME = BARBERRYS
SHORTNAME = Barberrys
TYPE = TR
CLASS = RN Transport
STATUS = SHIP_SUNK
XPOSITION = 529.1393433
ZPOSITION = 236.9507904
SPEED = 8.000000669
HEADING = 85
CURRENTHITPOINTS = 4755
CURRENTFLOATPOINTS = 3012
CURRENTFIRECOUNT = 0

PROPULSIONSYSTEMPERCENTAGE = 100
PROPULSIONSYSTEMDAMAGE = SYSTEM_OK
MANUEVERSYSTEMDIRECTION = Center
MANUEVERSYSTEMDAMAGE = 0
RADARDAMAGE = SYSTEM_OK
ELECTRICALSYSTEMDAMAGE = 0
BRIDGEDAMAGE = 0
DAMAGECONTROLPERCENTAGE = 100
DAMAGECONTROLDAMAGE = 0
TERTIARYGUNSCNT = 0
CIWPERCENTAGE = 100
CIWDAMAGE = 0
DIRECTOR1DAMAGE = SYSTEM_OK
DIRECTOR2DAMAGE = SYSTEM_OK

SECONDARYMAGDAMAGE = SYSTEM_OK
SECONDARYMAGHE = 0
SECONDARYMAGAP = 0
SECONDARYMAGCOM = 0
MAGADAMAGE = SYSTEM_OK
MAGAHE = 0
MAGAAP = 0
MAGACOM = 0
MAGBDAMAGE = SYSTEM_OK
MAGBHE = 0
MAGBAP = 0
MAGBCOM = 0

[SHIP6]

SIDE = ROYAL NAVY
NAME = CITY OF BATH
SHORTNAME = Cty Bath
TYPE = TR
CLASS = RN Transport
STATUS = SHIP_SUNK
XPOSITION = 968.0513916
ZPOSITION = 236.9507904
SPEED = 8.000000669
HEADING = 85
CURRENTHITPOINTS = 4755
CURRENTFLOATPOINTS = 3012
CURRENTFIRECOUNT = 0

PROPULSIONSYSTEMPERCENTAGE = 100
PROPULSIONSYSTEMDAMAGE = SYSTEM_OK
MANUEVERSYSTEMDIRECTION = Center
MANUEVERSYSTEMDAMAGE = 0
RADARDAMAGE = SYSTEM_OK
ELECTRICALSYSTEMDAMAGE = 0
BRIDGEDAMAGE = 0
DAMAGECONTROLPERCENTAGE = 100
DAMAGECONTROLDAMAGE = 0
TERTIARYGUNSCNT = 0
CIWPERCENTAGE = 100
CIWDAMAGE = 0
DIRECTOR1DAMAGE = SYSTEM_OK
DIRECTOR2DAMAGE = SYSTEM_OK

SECONDARYMAGDAMAGE = SYSTEM_OK
SECONDARYMAGHE = 0
SECONDARYMAGAP = 0
SECONDARYMAGCOM = 0
MAGADAMAGE = SYSTEM_OK
MAGAHE = 0
MAGAAP = 0
MAGACOM = 0
MAGBDAMAGE = SYSTEM_OK
MAGBHE = 0
MAGBAP = 0
MAGBCOM = 0

[SHIP7]

SIDE = ROYAL NAVY
NAME = CITY OF BOMBAY
SHORTNAME = Cty Bombay
TYPE = TR
CLASS = RN Transport
STATUS = SHIP_SUNK
XPOSITION = 529.1393433
ZPOSITION = -201.9611969
SPEED = 8.000000669
HEADING = 85
CURRENTHITPOINTS = 4755
CURRENTFLOATPOINTS = 3012
CURRENTFIRECOUNT = 0

PROPULSIONSYSTEMPERCENTAGE = 100
PROPULSIONSYSTEMDAMAGE = SYSTEM_OK
MANUEVERSYSTEMDIRECTION = Center
MANUEVERSYSTEMDAMAGE = 0
RADARDAMAGE = SYSTEM_OK
ELECTRICALSYSTEMDAMAGE = 0
BRIDGEDAMAGE = 0
DAMAGECONTROLPERCENTAGE = 100
DAMAGECONTROLDAMAGE = 0
TERTIARYGUNSCNT = 0
CIWPERCENTAGE = 100
CIWDAMAGE = 0
DIRECTOR1DAMAGE = SYSTEM_OK
DIRECTOR2DAMAGE = SYSTEM_OK

SECONDARYMAGDAMAGE = SYSTEM_OK
SECONDARYMAGHE = 0
SECONDARYMAGAP = 0
SECONDARYMAGCOM = 0
MAGADAMAGE = SYSTEM_OK
MAGAHE = 0
MAGAAP = 0
MAGACOM = 0
MAGBDAMAGE = SYSTEM_OK
MAGBHE = 0
MAGBAP = 0
MAGBCOM = 0

[SHIP8]

SIDE = ROYAL NAVY
NAME = CITY OF RIPON
SHORTNAME = Cty Ripon
TYPE = TR
CLASS = RN Transport
STATUS = SHIP_SUNK
XPOSITION = 968.0513916
ZPOSITION = -201.9611969
SPEED = 8.000000669
HEADING = 85
CURRENTHITPOINTS = 4755
CURRENTFLOATPOINTS = 3012
CURRENTFIRECOUNT = 0

PROPULSIONSYSTEMPERCENTAGE = 100
PROPULSIONSYSTEMDAMAGE = SYSTEM_OK
MANUEVERSYSTEMDIRECTION = Center
MANUEVERSYSTEMDAMAGE = 0
RADARDAMAGE = SYSTEM_OK
ELECTRICALSYSTEMDAMAGE = 0
BRIDGEDAMAGE = 0
DAMAGECONTROLPERCENTAGE = 100
DAMAGECONTROLDAMAGE = 0
TERTIARYGUNSCNT = 0
CIWPERCENTAGE = 100
CIWDAMAGE = 0
DIRECTOR1DAMAGE = SYSTEM_OK
DIRECTOR2DAMAGE = SYSTEM_OK

SECONDARYMAGDAMAGE = SYSTEM_OK
SECONDARYMAGHE = 0
SECONDARYMAGAP = 0
SECONDARYMAGCOM = 0
MAGADAMAGE = SYSTEM_OK
MAGAHE = 0
MAGAAP = 0
MAGACOM = 0
MAGBDAMAGE = SYSTEM_OK
MAGBHE = 0
MAGBAP = 0
MAGBCOM = 0

[SHIP0]

SIDE = KRIEGSMARINE
NAME = HIPPER
SHORTNAME = Hipper
TYPE = CA
CLASS = Hipper I
STATUS = SHIP_NORMAL
XPOSITION = -6747.505371
ZPOSITION = 13693.46484
SPEED = 20.22676061
HEADING = 80
CURRENTHITPOINTS = 16121
CURRENTFLOATPOINTS = 8061
CURRENTFIRECOUNT = 0

PROPULSIONSYSTEMPERCENTAGE = 100
PROPULSIONSYSTEMDAMAGE = SYSTEM_OK
MANUEVERSYSTEMDIRECTION = Center
MANUEVERSYSTEMDAMAGE = 0
RADARDAMAGE = SYSTEM_OK
ELECTRICALSYSTEMDAMAGE = 0
BRIDGEDAMAGE = 0
DAMAGECONTROLPERCENTAGE = 100
DAMAGECONTROLDAMAGE = 0
SEARCHLIGHTS1DAMAGE = SYSTEM_OK
SEARCHLIGHTP1DAMAGE = SYSTEM_OK
TERTIARYGUNSCNT = 0
CIWPERCENTAGE = 100
CIWDAMAGE = 0
DIRECTOR1DAMAGE = SYSTEM_OK
DIRECTOR2DAMAGE = SYSTEM_OK
TORPMOUNT1TORPSLEFT = 3
TORPMOUNT1DAMAGE = SYSTEM_OK
TORPMOUNT2TORPSLEFT = 3
TORPMOUNT2DAMAGE = SYSTEM_OK
TORPMOUNT3TORPSLEFT = 3
TORPMOUNT3DAMAGE = SYSTEM_OK
TORPMOUNT4TORPSLEFT = 3
TORPMOUNT4DAMAGE = SYSTEM_OK

SECONDARYGUNSPORTCNT = 3
SECONDARYGUNSSTBCNT = 3
SECONDARYMAGDAMAGE = SYSTEM_OK
SECONDARYMAGHE = 0
SECONDARYMAGAP = 0
SECONDARYMAGCOM = 4800
MGTA = SYSTEM_OK
MGTB = SYSTEM_OK
MGTY = SYSTEM_OK
MGTZ = SYSTEM_OK
MAGADAMAGE = SYSTEM_OK
MAGAHE = 170
MAGAAP = 227
MAGACOM = 170
MAGBDAMAGE = SYSTEM_OK
MAGBHE = 170
MAGBAP = 227
MAGBCOM = 170

[SHIP1]

SIDE = KRIEGSMARINE
NAME = FRIEDRICH ECKOLDT
SHORTNAME = Fredrc Eck
TYPE = DD
CLASS = 1934A Type
STATUS = SHIP_NORMAL
XPOSITION = -11992.33105
ZPOSITION = -1563.64978
SPEED = 20.0494915
HEADING = 75
CURRENTHITPOINTS = 3165
CURRENTFLOATPOINTS = 2220
CURRENTFIRECOUNT = 0

PROPULSIONSYSTEMPERCENTAGE = 100
PROPULSIONSYSTEMDAMAGE = SYSTEM_OK
MANUEVERSYSTEMDIRECTION = Center
MANUEVERSYSTEMDAMAGE = 0
RADARDAMAGE = SYSTEM_OK
ELECTRICALSYSTEMDAMAGE = 0
BRIDGEDAMAGE = 0
DAMAGECONTROLPERCENTAGE = 100
DAMAGECONTROLDAMAGE = 0
SEARCHLIGHTP1DAMAGE = SYSTEM_OK
SEARCHLIGHTS1DAMAGE = SYSTEM_OK
TERTIARYGUNSCNT = 0
CIWPERCENTAGE = 100
CIWDAMAGE = 0
DIRECTOR1DAMAGE = SYSTEM_OK
DIRECTOR2DAMAGE = SYSTEM_OK
TORPMOUNT1TORPSLEFT = 4
TORPMOUNT1DAMAGE = SYSTEM_OK
TORPMOUNT2TORPSLEFT = 4
TORPMOUNT2DAMAGE = SYSTEM_OK

SECONDARYMAGDAMAGE = SYSTEM_OK
SECONDARYMAGHE = 0
SECONDARYMAGAP = 0
SECONDARYMAGCOM = 0
MGTA = SYSTEM_OK
MGTB = SYSTEM_OK
MGTL = SYSTEM_OK
MGTY = SYSTEM_OK
MGTZ = SYSTEM_OK
MAGADAMAGE = SYSTEM_OK
MAGAHE = 0
MAGAAP = 0
MAGACOM = 240
MAGBDAMAGE = SYSTEM_OK
MAGBHE = 0
MAGBAP = 0
MAGBCOM = 360

[SHIP2]

SIDE = KRIEGSMARINE
NAME = RICHARD BEITZEN
SHORTNAME = Rich Btzen
TYPE = DD
CLASS = 1934A Type
STATUS = SHIP_NORMAL
XPOSITION = -12892.64844
ZPOSITION = -1723.364258
SPEED = 20.0494915
HEADING = 80
CURRENTHITPOINTS = 3165
CURRENTFLOATPOINTS = 2220
CURRENTFIRECOUNT = 0

PROPULSIONSYSTEMPERCENTAGE = 100
PROPULSIONSYSTEMDAMAGE = SYSTEM_OK
MANUEVERSYSTEMDIRECTION = Center
MANUEVERSYSTEMDAMAGE = 0
RADARDAMAGE = SYSTEM_OK
ELECTRICALSYSTEMDAMAGE = 0
BRIDGEDAMAGE = 0
DAMAGECONTROLPERCENTAGE = 100
DAMAGECONTROLDAMAGE = 0
SEARCHLIGHTP1DAMAGE = SYSTEM_OK
SEARCHLIGHTS1DAMAGE = SYSTEM_OK
TERTIARYGUNSCNT = 0
CIWPERCENTAGE = 100
CIWDAMAGE = 0
DIRECTOR1DAMAGE = SYSTEM_OK
DIRECTOR2DAMAGE = SYSTEM_OK
TORPMOUNT1TORPSLEFT = 4
TORPMOUNT1DAMAGE = SYSTEM_OK
TORPMOUNT2TORPSLEFT = 4
TORPMOUNT2DAMAGE = SYSTEM_OK

SECONDARYMAGDAMAGE = SYSTEM_OK
SECONDARYMAGHE = 0
SECONDARYMAGAP = 0
SECONDARYMAGCOM = 0
MGTA = SYSTEM_OK
MGTB = SYSTEM_OK
MGTL = SYSTEM_OK
MGTY = SYSTEM_OK
MGTZ = SYSTEM_OK
MAGADAMAGE = SYSTEM_OK
MAGAHE = 0
MAGAAP = 0
MAGACOM = 240
MAGBDAMAGE = SYSTEM_OK
MAGBHE = 0
MAGBAP = 0
MAGBCOM = 360

[SHIP3]

SIDE = KRIEGSMARINE
NAME = Z29
SHORTNAME = Z29
TYPE = DD
CLASS = 1936A Type
STATUS = SHIP_NORMAL
XPOSITION = -13793.15723
ZPOSITION = -1882.148315
SPEED = 20.0494915
HEADING = 80
CURRENTHITPOINTS = 3785
CURRENTFLOATPOINTS = 2553
CURRENTFIRECOUNT = 0

PROPULSIONSYSTEMPERCENTAGE = 100
PROPULSIONSYSTEMDAMAGE = SYSTEM_OK
MANUEVERSYSTEMDIRECTION = Center
MANUEVERSYSTEMDAMAGE = 0
RADARDAMAGE = SYSTEM_OK
ELECTRICALSYSTEMDAMAGE = 0
BRIDGEDAMAGE = 0
DAMAGECONTROLPERCENTAGE = 100
DAMAGECONTROLDAMAGE = 0
SEARCHLIGHTP1DAMAGE = SYSTEM_OK
SEARCHLIGHTS1DAMAGE = SYSTEM_OK
TERTIARYGUNSCNT = 0
CIWPERCENTAGE = 100
CIWDAMAGE = 0
DIRECTOR1DAMAGE = SYSTEM_OK
DIRECTOR2DAMAGE = SYSTEM_OK
TORPMOUNT1TORPSLEFT = 4
TORPMOUNT1DAMAGE = SYSTEM_OK
TORPMOUNT2TORPSLEFT = 4
TORPMOUNT2DAMAGE = SYSTEM_OK

SECONDARYMAGDAMAGE = SYSTEM_OK
SECONDARYMAGHE = 0
SECONDARYMAGAP = 0
SECONDARYMAGCOM = 0
MGTA = SYSTEM_OK
MGTL = SYSTEM_OK
MGTY = SYSTEM_OK
MGTZ = SYSTEM_OK
MAGADAMAGE = SYSTEM_OK
MAGAHE = 120
MAGAAP = 120
MAGACOM = 0
MAGBDAMAGE = SYSTEM_OK
MAGBHE = 180
MAGBAP = 180
MAGBCOM = 0
