[VERSION]
VERSIONNUMBER=64

[SCENARIODATA]
TITLE = Barents Sea 1
FINISH_TIME_HOUR=9
FINISH_TIME_MINUTE=0

[SHIP0]

SIDE = ROYAL NAVY
NAME = ONSLOW
SHORTNAME = Onslow
TYPE = DD
CLASS = OP Class
STATUS = SHIP_SUNK
XPOSITION = 523.1762695
ZPOSITION = 2106.779785
SPEED = 8.000000669
HEADING = 85
CURRENTHITPOINTS = 2497
CURRENTFLOATPOINTS = 1827
CURRENTFIRECOUNT = 0

PROPULSIONSYSTEMPERCENTAGE = 100
PROPULSIONSYSTEMDAMAGE = SYSTEM_OK
MANUEVERSYSTEMDIRECTION = Center
MANUEVERSYSTEMDAMAGE = 0
RADARDAMAGE = SYSTEM_OK
ELECTRICALSYSTEMDAMAGE = 0
BRIDGEDAMAGE = 0
DAMAGECONTROLPERCENTAGE = 100
DAMAGECONTROLDAMAGE = 0
SEARCHLIGHTP1DAMAGE = SYSTEM_OK
SEARCHLIGHTS1DAMAGE = SYSTEM_OK
TERTIARYGUNSCNT = 0
CIWPERCENTAGE = 100
CIWDAMAGE = 0
DIRECTOR1DAMAGE = SYSTEM_OK
DIRECTOR2DAMAGE = SYSTEM_OK
TORPMOUNT1TORPSLEFT = 4
TORPMOUNT1DAMAGE = SYSTEM_OK
TORPMOUNT2TORPSLEFT = 4
TORPMOUNT2DAMAGE = SYSTEM_OK

SECONDARYMAGDAMAGE = SYSTEM_OK
SECONDARYMAGHE = 0
SECONDARYMAGAP = 0
SECONDARYMAGCOM = 0
MGTA = SYSTEM_OK
MGTB = SYSTEM_OK
MGTY = SYSTEM_OK
MGTZ = SYSTEM_OK
MAGADAMAGE = SYSTEM_OK
MAGAHE = 0
MAGAAP = 0
MAGACOM = 500
MAGBDAMAGE = SYSTEM_OK
MAGBHE = 0
MAGBAP = 0
MAGBCOM = 500

[SHIP1]

SIDE = ROYAL NAVY
NAME = ORWELL
SHORTNAME = Orwell
TYPE = DD
CLASS = OP Class
STATUS = SHIP_SUNK
XPOSITION = -205.5601196
ZPOSITION = 2043.02356
SPEED = 8.000000669
HEADING = 85
CURRENTHITPOINTS = 2497
CURRENTFLOATPOINTS = 1827
CURRENTFIRECOUNT = 0

PROPULSIONSYSTEMPERCENTAGE = 100
PROPULSIONSYSTEMDAMAGE = SYSTEM_OK
MANUEVERSYSTEMDIRECTION = Center
MANUEVERSYSTEMDAMAGE = 0
RADARDAMAGE = SYSTEM_OK
ELECTRICALSYSTEMDAMAGE = 0
BRIDGEDAMAGE = 0
DAMAGECONTROLPERCENTAGE = 100
DAMAGECONTROLDAMAGE = 0
SEARCHLIGHTP1DAMAGE = SYSTEM_OK
SEARCHLIGHTS1DAMAGE = SYSTEM_OK
TERTIARYGUNSCNT = 0
CIWPERCENTAGE = 100
CIWDAMAGE = 0
DIRECTOR1DAMAGE = SYSTEM_OK
DIRECTOR2DAMAGE = SYSTEM_OK
TORPMOUNT1TORPSLEFT = 4
TORPMOUNT1DAMAGE = SYSTEM_OK
TORPMOUNT2TORPSLEFT = 4
TORPMOUNT2DAMAGE = SYSTEM_OK

SECONDARYMAGDAMAGE = SYSTEM_OK
SECONDARYMAGHE = 0
SECONDARYMAGAP = 0
SECONDARYMAGCOM = 0
MGTA = SYSTEM_OK
MGTB = SYSTEM_OK
MGTY = SYSTEM_OK
MGTZ = SYSTEM_OK
MAGADAMAGE = SYSTEM_OK
MAGAHE = 0
MAGAAP = 0
MAGACOM = 500
MAGBDAMAGE = SYSTEM_OK
MAGBHE = 0
MAGBAP = 0
MAGBCOM = 500

[SHIP0]

SIDE = KRIEGSMARINE
NAME = HIPPER
SHORTNAME = Hipper
TYPE = CA
CLASS = Hipper I
STATUS = SHIP_NORMAL
XPOSITION = -6747.505371
ZPOSITION = 13693.46484
SPEED = 20.22676061
HEADING = 80
CURRENTHITPOINTS = 16121
CURRENTFLOATPOINTS = 8061
CURRENTFIRECOUNT = 0

PROPULSIONSYSTEMPERCENTAGE = 100
PROPULSIONSYSTEMDAMAGE = SYSTEM_OK
MANUEVERSYSTEMDIRECTION = Center
MANUEVERSYSTEMDAMAGE = 0
RADARDAMAGE = SYSTEM_OK
ELECTRICALSYSTEMDAMAGE = 0
BRIDGEDAMAGE = 0
DAMAGECONTROLPERCENTAGE = 100
DAMAGECONTROLDAMAGE = 0
SEARCHLIGHTS1DAMAGE = SYSTEM_OK
SEARCHLIGHTP1DAMAGE = SYSTEM_OK
TERTIARYGUNSCNT = 0
CIWPERCENTAGE = 100
CIWDAMAGE = 0
DIRECTOR1DAMAGE = SYSTEM_OK
DIRECTOR2DAMAGE = SYSTEM_OK
TORPMOUNT1TORPSLEFT = 3
TORPMOUNT1DAMAGE = SYSTEM_OK
TORPMOUNT2TORPSLEFT = 3
TORPMOUNT2DAMAGE = SYSTEM_OK
TORPMOUNT3TORPSLEFT = 3
TORPMOUNT3DAMAGE = SYSTEM_OK
TORPMOUNT4TORPSLEFT = 3
TORPMOUNT4DAMAGE = SYSTEM_OK

SECONDARYGUNSPORTCNT = 3
SECONDARYGUNSSTBCNT = 3
SECONDARYMAGDAMAGE = SYSTEM_OK
SECONDARYMAGHE = 0
SECONDARYMAGAP = 0
SECONDARYMAGCOM = 4800
MGTA = SYSTEM_OK
MGTB = SYSTEM_OK
MGTY = SYSTEM_OK
MGTZ = SYSTEM_OK
MAGADAMAGE = SYSTEM_OK
MAGAHE = 170
MAGAAP = 227
MAGACOM = 170
MAGBDAMAGE = SYSTEM_OK
MAGBHE = 170
MAGBAP = 227
MAGBCOM = 170

[SHIP1]

SIDE = KRIEGSMARINE
NAME = Z29
SHORTNAME = Z29
TYPE = DD
CLASS = 1936A Type
STATUS = SHIP_NORMAL
XPOSITION = -13793.15723
ZPOSITION = -1882.148315
SPEED = 20.0494915
HEADING = 80
CURRENTHITPOINTS = 3785
CURRENTFLOATPOINTS = 2553
CURRENTFIRECOUNT = 0

PROPULSIONSYSTEMPERCENTAGE = 100
PROPULSIONSYSTEMDAMAGE = SYSTEM_OK
MANUEVERSYSTEMDIRECTION = Center
MANUEVERSYSTEMDAMAGE = 0
RADARDAMAGE = SYSTEM_OK
ELECTRICALSYSTEMDAMAGE = 0
BRIDGEDAMAGE = 0
DAMAGECONTROLPERCENTAGE = 100
DAMAGECONTROLDAMAGE = 0
SEARCHLIGHTP1DAMAGE = SYSTEM_OK
SEARCHLIGHTS1DAMAGE = SYSTEM_OK
TERTIARYGUNSCNT = 0
CIWPERCENTAGE = 100
CIWDAMAGE = 0
DIRECTOR1DAMAGE = SYSTEM_OK
DIRECTOR2DAMAGE = SYSTEM_OK
TORPMOUNT1TORPSLEFT = 4
TORPMOUNT1DAMAGE = SYSTEM_OK
TORPMOUNT2TORPSLEFT = 4
TORPMOUNT2DAMAGE = SYSTEM_OK

SECONDARYMAGDAMAGE = SYSTEM_OK
SECONDARYMAGHE = 0
SECONDARYMAGAP = 0
SECONDARYMAGCOM = 0
MGTA = SYSTEM_OK
MGTL = SYSTEM_OK
MGTY = SYSTEM_OK
MGTZ = SYSTEM_OK
MAGADAMAGE = SYSTEM_OK
MAGAHE = 120
MAGAAP = 120
MAGACOM = 0
MAGBDAMAGE = SYSTEM_OK
MAGBHE = 180
MAGBAP = 180
MAGBCOM = 0
