<?php

declare(strict_types=1);

/**
 * @author     Eric COURTIAL <e.courtial30@gmail.com>
 * @date       06/04/2020 (dd-mm-YYYY)
 */

namespace App\NameSwitcher\Transformer;

class Ship
{
    // The name in TAS, as expected to be find in the scenario generated by TAS
    protected string $originalName;
    // Then name to set
    protected string $name;
    // The Shortname to set
    protected string $shortName;

    public function __construct(string $originalName, string $name, string $shortName)
    {
        $this->originalName = $originalName;
        $this->name = $name;
        $this->shortName = $shortName;
    }

    public function getOriginalName(): string
    {
        return $this->originalName;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function getShortName(): string
    {
        return $this->shortName;
    }

    public function setShortName(string $shortName): self
    {
        $this->shortName = $shortName;

        return $this;
    }
}
